import { Router, Request, Response } from 'express';
import { randomUUID } from 'crypto';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { createMcpServer } from './server';

const router = Router();

/**
 * In-memory session store.
 * Key: session ID (generated by the transport on initialize).
 * Value: the transport instance for that session.
 *
 * One McpServer + transport instance is created per client connection,
 * which avoids shared-state issues across concurrent clients.
 */
const transports = new Map<string, StreamableHTTPServerTransport>();

/**
 * Single endpoint that handles all MCP Streamable HTTP traffic:
 *   - POST with no mcp-session-id  → new session (initialize)
 *   - POST with mcp-session-id     → send message to existing session
 *   - GET  with mcp-session-id     → open SSE stream for existing session
 *   - DELETE with mcp-session-id   → close session
 *
 * The transport automatically returns:
 *   - 400 for non-initialize requests that arrive without a session ID
 *   - 404 for requests referencing an unknown session ID (after we check the map)
 */
router.all('/', async (req: Request, res: Response) => {
  const sessionId = req.headers['mcp-session-id'] as string | undefined;

  if (sessionId) {
    // Route to existing session transport
    const transport = transports.get(sessionId);
    if (!transport) {
      res.status(404).json({ error: 'Session not found', sessionId });
      return;
    }
    try {
      await transport.handleRequest(req, res, req.body);
    } catch (err) {
      console.error('[MCP] transport error on existing session', err);
      if (!res.headersSent) {
        res.status(500).json({ error: 'Internal server error' });
      }
    }
    return;
  }

  // No session ID — create a new session for this connection attempt
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: () => randomUUID(),
    onsessioninitialized: (id) => {
      transports.set(id, transport);
    },
    onsessionclosed: (id) => {
      transports.delete(id);
    },
  });

  transport.onclose = () => {
    if (transport.sessionId) {
      transports.delete(transport.sessionId);
    }
  };

  try {
    const mcpServer = createMcpServer();
    await mcpServer.connect(transport);
    await transport.handleRequest(req, res, req.body);
  } catch (err) {
    console.error('[MCP] transport error on new session', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Internal server error' });
    }
  }
});

export default router;
